version: '3.5'

services:

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic

    healthcheck:
      test: curl http://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5
    #mount deployed mysql filesystem location for persistance

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic
    #mount deployed mysql filesystem location for persistance

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic
    #mount deployed mysql filesystem location for persistance

  kib01:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: kib01
    depends_on: {"es01": {"condition": "service_healthy"}}
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - elastic
    ports:
      - "5601:5601"

  activemq:
    image: rmohr/activemq:5.10.0 
    container_name: activemq
    networks:
      - elastic

  mysqldb:
    image: mysql:latest
    restart: always
    container_name: mysqldb
    environment:
      - MYSQL_DATABASE=telemetrysource_services_db #specify configured database name
      - MYSQL_USER=reftools           #sample reference - specify configured username
      - MYSQL_PASSWORD=*Ref!**lsq8#v* #sample reference - specify configured credentials
      - MYSQL_ROOT_PASSWORD=""        #sample reference - specify configured credentials
    networks:
      - elastic
    #mount deployed mysql filesystem location for persistance

  telemetry-receiver:
    image: golang:1.15
    container_name: telemetry-receiver
    volumes:
      - ./../.:/go/src/github.com/telemetry-reference-tools
    working_dir: 
      /go/src/github.com/telemetry-reference-tools
    environment:
      - MESSAGEBUS_HOST=activemq      #sample reference - specify messagebus hostname
      - MESSAGEBUS_PORT=61613         #sample reference - specify messagebus port
      - CONFIGUI_HTTP_PORT=8082       #sample reference - specify web application port
      - MYSQL_DATABASE=telemetrysource_services_db #sample reference - specify configured database name
      - MYSQL_USER=reftools           #sample reference - specify configured username
      - MYSQL_PASSWORD=*Ref!**lsq8#v* #sample reference - specify configured credentials
      - MYSQL_HOST=mysqldb            #sample reference - specify mysql hostname
      - MYSQL_HOST_PORT=3306          #sample reference - specify mysql port number
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        cmd/idrac-telemetry-receiver.sh
    networks:
      - elastic
    depends_on:
      - "activemq"
      - "mysqldb"
    ports:
      - "8082:8082"

  es-ingester:
    image: golang:1.15
    container_name: es-ingester
    volumes:
      - ./../.:/go/src/github.com/telemetry-reference-tools
    working_dir: 
      /go/src/github.com/telemetry-reference-tools
    command:
      go run cmd/elkpump/elkpump-basic.go
    networks:
      - elastic
    depends_on:
      - "activemq"
      - "es01"

    environment:
      - MESSAGEBUS_HOST=activemq      #sample reference - specify messagebus hostname
      - MESSAGEBUS_PORT=61613         #sample reference - specify messagebus port
      - ELASTICSEARCH_URL=http://es01:9200

networks:
  elastic:
    driver: bridge

volumes:
  mysql-db:
