version: '3.5'

services:
  influx:
    image: influxdb:1.8
    volumes:
      - influxdb-storage:/var/lib/influxdb
    container_name: influx
    environment:
      - node.name=influx
      - INFLUXDB_DB=poweredge_telemetry_metrics
    networks:
      - influxpipeline
    healthcheck:
      test: curl http://localhost:8086 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on: 
      - "influx"

    container_name: grafana
    environment:
      - INFLUXDB_URL=http://influxdb:8086
    networks:
      - influxpipeline

  activemq:
    image: rmohr/activemq:5.10.0 
    container_name: activemq
    networks:
      - influxpipeline

  mysqldb:
    image: mysql:latest
    restart: always
    container_name: mysqldb
    environment:
      - MYSQL_DATABASE=telemetrysource_services_db #specify configured database name
      - MYSQL_USER=reftools           #sample reference - specify configured user name
      - MYSQL_PASSWORD=*Ref!**lsq8#v* #sample reference - specify configured credentials
      - MYSQL_ROOT_PASSWORD=""        #sample reference - specify configured credentials
    networks:
      - influxpipeline
    #mount deployed mysql filesystem location for persistance

  telemetry-receiver:
    image: golang:1.15
    container_name: telemetry-receiver
    volumes:
      - ./../.:/go/src/github.com/telemetry-reference-tools
    working_dir: 
      /go/src/github.com/telemetry-reference-tools
    environment:
      - MESSAGEBUS_HOST=activemq      #sample reference - specify messagebus hostname
      - MESSAGEBUS_PORT=61613         #sample reference - specify messagebus port
      - CONFIGUI_HTTP_PORT=8082       #sample reference - specify web application port
      - MYSQL_DATABASE=telemetrysource_services_db #sample reference - specify configured database name
      - MYSQL_USER=reftools           #sample reference - specify configured user name
      - MYSQL_PASSWORD=*Ref!**lsq8#v* #sample reference - specify configured credentials
      - MYSQL_HOST=mysqldb            #sample reference - specify mysql hostname
      - MYSQL_HOST_PORT=3306          #sample reference - specify mysql port number
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        cmd/idrac-telemetry-receiver.sh
    networks:
      - influxpipeline
    depends_on:
      - "activemq"
      - "mysqldb"
    ports:
      - "8082:8082"

  influx-ingester:
    image: golang:1.15
    container_name: influx-ingester
    volumes:
      - ./../.:/go/src/github.com/telemetry-reference-tools
    working_dir: 
      /go/src/github.com/telemetry-reference-tools
    command:
      go run cmd/influxpump/influxpump.go
    environment:
      - MESSAGEBUS_HOST=activemq      #sample reference - specify messagebus hostname
      - MESSAGEBUS_PORT=61613         #sample reference - specify messagebus port
      - INFLUXDB_SERVER=influx
      - INFLUXDB_DB=poweredge_telemetry_metrics
    networks:
      - influxpipeline
    depends_on:
      - "activemq"
      - "influx"  

networks:
  influxpipeline:
    driver: bridge

volumes:
  influxdb-storage:
  grafana-storage:
