version: '3.1'

services:
  prometheus:
    image: prom/prometheus:v2.1.0
    restart: always
    container_name: prometheus
    volumes:
      - ./../.:/go/src/github.com/telemetry-reference-tools
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    working_dir:
      /go/src/github.com/telemetry-reference-tools
    environment:
      - node.name=prometheus
      - PROMETHEUS_DB=poweredge_telemetry_metrics
    command:
      - '--config.file=cmd/prometheuspump/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - prometheuspipeline

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      - prometheuspipeline

  activemq:
    image: rmohr/activemq:5.10.0 
    container_name: activemq
    networks:
      - prometheuspipeline

  mysqldb:
    image: mysql:latest
    restart: always
    container_name: mysqldb
    environment:
      - MYSQL_DATABASE=telemetrysource_services_db #specify configured database name
      - MYSQL_USER=reftools           #sample reference - specify configured user name
      - MYSQL_PASSWORD=*Ref!**lsq8#v* #sample reference - specify configured credentials
      - MYSQL_ROOT_PASSWORD=""        #sample reference - specify configured credentials
    networks:
      - prometheuspipeline
    #mount deployed mysql filesystem location for persistance

  telemetry-receiver:
    image: golang:1.15
    container_name: telemetry-receiver
    volumes:
      - ./../.:/go/src/github.com/telemetry-reference-tools
    working_dir: 
      /go/src/github.com/telemetry-reference-tools
    environment:
      - MESSAGEBUS_HOST=activemq      #sample reference - specify messagebus hostname
      - MESSAGEBUS_PORT=61613         #sample reference - specify messagebus port
      - CONFIGUI_HTTP_PORT=8082       #sample reference - specify web application port
      - MYSQL_DATABASE=telemetrysource_services_db #sample reference - specify configured database name
      - MYSQL_USER=reftools           #sample reference - specify configured user name
      - MYSQL_PASSWORD=*Ref!**lsq8#v* #sample reference - specify configured credentials
      - MYSQL_HOST=mysqldb            #sample reference - specify mysql hostname
      - MYSQL_HOST_PORT=3306          #sample reference - specify mysql port number
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        cmd/idrac-telemetry-receiver.sh
    networks:
      - prometheuspipeline
    depends_on:
      - "activemq"
      - "mysqldb"

  prometheus-ingester:
    image: golang:1.15
    container_name: prometheus-ingester
    volumes:
      - ./../.:/go/src/github.com/telemetry-reference-tools
    working_dir: 
      /go/src/github.com/telemetry-reference-tools
    command:
      go run cmd/prometheuspump/prometheuspump.go
    environment:
      - MESSAGEBUS_HOST=activemq      #sample reference - specify messagebus hostname
      - MESSAGEBUS_PORT=61613         #sample reference - specify messagebus port
      - PROMETHEUSDB_SERVER=prometheus
    networks:
      - prometheuspipeline
    depends_on:
      - "activemq"

volumes:
    prometheus_data: {}

networks:
  prometheuspipeline:
    driver: bridge
