version: '3.5'

services:

  activemq:
    image: rmohr/activemq:5.10.0
    container_name: activemq
    networks:
      - splunk
    ports:
      - "8161:8161"
      - "61613:61613"

  mysqldb:
    image: mysql:latest
    restart: always
    container_name: mysqldb
    environment:
      - MYSQL_DATABASE=telemetrysource_services_db #specify configured database name
      - MYSQL_USER=reftools           #sample reference - specify configured username
      - MYSQL_PASSWORD=*Ref!**lsq8#v* #sample reference - specify configured credentials
      - MYSQL_ROOT_PASSWORD=""        #sample reference - specify configured credentials
    networks:
      - splunk
    volumes:
      - "mysqldb_volume:/var/lib/mysql:rw"

  telemetry-receiver:
    image: golang:1.15
    container_name: telemetry-receiver
    stdin_open: true
    tty: true
    volumes:
      - ./../.:/go/src/github.com/telemetry-reference-tools
    working_dir:
      /go/src/github.com/telemetry-reference-tools
    environment:
      - MESSAGEBUS_HOST=activemq      #sample reference - specify messagebus hostname
      - MESSAGEBUS_PORT=61613         #sample reference - specify messagebus port
      - CONFIGUI_HTTP_PORT=8082       #sample reference - specify web application port
      - MYSQL_DATABASE=telemetrysource_services_db #sample reference - specify configured database name
      - MYSQL_USER=reftools           #sample reference - specify configured username
      - MYSQL_PASSWORD=*Ref!**lsq8#v* #sample reference - specify configured credentials
      - MYSQL_HOST=mysqldb            #sample reference - specify mysql hostname
      - MYSQL_HOST_PORT=3306          #sample reference - specify mysql port number
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        cmd/idrac-telemetry-receiver.sh
    networks:
      - splunk
    depends_on:
      - "activemq"
      - "mysqldb"
    ports:
      - "8082:8082"

  splunkpump:
    image: golang:1.15
    container_name: splunkpump
    volumes:
      - ./../.:/go/src/github.com/telemetry-reference-tools
    working_dir:
      /go/src/github.com/telemetry-reference-tools
    command:
      go run cmd/splunkpump/splunkpump.go
    networks:
      - splunk
    depends_on:
      - "activemq"
    environment:
      - MESSAGEBUS_HOST=activemq      #sample reference - specify messagebus hostname
      - MESSAGEBUS_PORT=61613         #sample reference - specify messagebus port
      - SPLUNK_URL=http://192.168.1.5:8088
      - SPLUNK_KEY=87b52214-1950-4b22-8fd7-f57543431b81

networks:
  splunk:
    driver: bridge

volumes:
  mysqldb_volume: