version: '3.1'

services:
  timescale:
    image: timescale/timescaledb:latest-pg12
    container_name: timescale
    volumes:
      - ./../.:/go/src/github.com/telemetry-reference-tools
    working_dir: 
      /go/src/github.com/telemetry-reference-tools
    restart: always
    environment:
      - node.name=timescale
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TIMESCALE_DB=poweredge_telemetry_metrics
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        cmd/initialize_timescaledb.sh
    networks:
      - timescalepipeline

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      - timescalepipeline

  activemq:
    image: rmohr/activemq:5.10.0 
    container_name: activemq
    networks:
      - timescalepipeline


  mysqldb:
    image: mysql:latest
    restart: always
    container_name: mysqldb
    environment:
      - MYSQL_DATABASE=telemetrysource_services_db #specify configured database name
      - MYSQL_USER=reftools           #sample reference - specify configured user name
      - MYSQL_PASSWORD=*Ref!**lsq8#v* #sample reference - specify configured credentials
      - MYSQL_ROOT_PASSWORD=""        #sample reference - specify configured credentials
    networks:
      - timescalepipeline
    #mount deployed mysql filesystem location for persistance

  telemetry-receiver:
    image: golang:1.15
    container_name: telemetry-receiver
    volumes:
      - ./../.:/go/src/github.com/telemetry-reference-tools
    working_dir: 
      /go/src/github.com/telemetry-reference-tools
    environment:
      - MESSAGEBUS_HOST=activemq      #sample reference - specify messagebus hostname
      - MESSAGEBUS_PORT=61613         #sample reference - specify messagebus port
      - CONFIGUI_HTTP_PORT=8082       #sample reference - specify web application port
      - MYSQL_DATABASE=telemetrysource_services_db #sample reference - specify configured database name
      - MYSQL_USER=reftools           #sample reference - specify configured user name
      - MYSQL_PASSWORD=*Ref!**lsq8#v* #sample reference - specify configured credentials
      - MYSQL_HOST=mysqldb            #sample reference - specify mysql hostname
      - MYSQL_HOST_PORT=3306          #sample reference - specify mysql port number
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        cmd/idrac-telemetry-receiver.sh
    networks:
      - timescalepipeline
    depends_on:
      - "activemq"
      - "mysqldb"
    ports:
      - "8082:8082"

  timescale-ingester:
    image: golang:1.15
    container_name: timescale-ingester
    volumes:
      - ./../.:/go/src/github.com/telemetry-reference-tools
    working_dir: 
      /go/src/github.com/telemetry-reference-tools
    command:
      go run cmd/timescalepump/timescalepump.go
    environment:
      - MESSAGEBUS_HOST=activemq      #sample reference - specify messagebus hostname
      - MESSAGEBUS_PORT=61613         #sample reference - specify messagebus port
      - POSTGRES_USER=postgres
      - POSTGRES_DEFAULT_PWD=postgres
      - TIMESCALE_SERVER=timescale
      - TIMESCALE_DB=poweredge_telemetry_metrics
    networks:
      - timescalepipeline
    depends_on:
      - "activemq"

networks:
  timescalepipeline:
    driver: bridge
